print("The {noun} was {verbing} down by the place when suddenly a {noun} fell from the sky.")
print("The crash made everyone {verb}.")
print("So {adjective} was this unexpected event, that it even made the {nouns} {past tense verb}.")
print("By the time everything calmed down, it became clear that it had only happened in {noun’s} dream.")
print("Upon awakening, the {adjective} day continued normally.")

noun = input("Enter a noun.: ")
plural_noun = input("Enter plural noun.: ")
possesive_noun = input("Enter possesive noun.: ")
verbing = input('Enter a verb ending in "ing.": ')
verb = input("Enter a verb.: ")
adjective = input("Enter an adjective.: ")
past_tense_verb = input("Enter a past tense verb.: ")
